name: Check

permissions: {}

on:
  pull_request:
  merge_group:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Check GitHub Actions
        uses: zizmorcore/zizmor-action@135698455da5c3b3e55f73f4419e481ab68cdd95

      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version-file: .nvmrc

      - name: Set up tflint
        uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@c2a20b1822cc4a6bc594ff7f1dbb658758e383c3
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JSON Schema CLI
        uses: sourcemeta/jsonschema@a6a55d7f3a43487503f52defc19f04ff237a036d

      - name: Set up cfn-lint
        uses: scottbrenner/cfn-lint-action@25ee47d1ab3146bda904df745511735cc0b9a970

      - name: Install dependencies
        run: npm ci && cd solutions/integration-tests && npm ci

      - name: Check types
        run: npm run check-types

      - name: Check Dependencies
        run: npm run audit

      - name: ESLint
        run: npm run eslint

      - name: Lint Terraform
        run: npm run tflint

      - name: SAM validate frontend
        run: npm run sam-validate:frontend

      - name: SAM validate API
        run: npm run sam-validate:api

      - name: SAM validate stubs
        run: npm run sam-validate:stubs

      - name: SAM validate core
        run: npm run sam-validate:core

      - name: Lint CloudFormation
        run: npm run cfnlint

      - name: Check formatting
        run: npm run format

      - name: Knip
        run: npm run knip

      - name: Validate config
        run: npm run config:validate

      - name: Validate API Specs
        run: npm run api-specs:validate

      - name: Build core
        run: npm run build:core

      - name: Build frontend
        run: npm run build:frontend

      - name: Build stubs
        run: npm run build:stubs

      - name: Build API
        run: npm run build:api
