name: Production - Deploy Configuration

on:
  push:
    branches:
      - main
    paths:
      - "solutions/config/production-config.json"
      - ".github/workflows/deploy-config.yaml"
      - ".github/workflows/deploy-config-production.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Config (Production)
    uses: ./.github/workflows/deploy-config.yaml
    permissions:
      id-token: write
      contents: read
    with:
      gh-environment: build
      target-environment: production
      config-file: production-config.json
    secrets:
      config-source-bucket-name: ${{ secrets.APP_CONFIG_SOURCE_BUCKET_NAME }}
      aws-role-arn: ${{ secrets.GHA_APP_CONFIG_ROLE_ARN }}
      aws-artefact-signing-key-arn: ${{ secrets.CONFIG_SIGNING_KEY_ARN }}
