name: Deploy stubs

permissions: {}

on:
  push:
    branches:
      - main
    paths:
      - solutions/stubs/**
      - solutions/commons/**
      - .github/workflows/deploy-stubs.yaml
      - package.json
      - package-lock.json
      - .npmrc
      - .nvmrc
      - tsconfig.json

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy-stubs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version-file: .nvmrc

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@c2a20b1822cc4a6bc594ff7f1dbb658758e383c3
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN_MOCKS }}
          aws-region: "eu-west-2"

      - name: Install dependencies
        run: npm ci

      - name: Build stubs
        run: npm run build:stubs

      - name: Deploy stubs
        uses: govuk-one-login/devplatform-upload-action@abbf25e43a88b3512b1a43621f9aef4cbea1b648
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_BUCKET_NAME_MOCKS }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: ./solutions/stubs
          template-file: .aws-sam/build/template.yaml
