name: Deploy stubs to dev

on:
  workflow_dispatch:
    inputs:
      refType:
        type: choice
        description: "Find branch name, commit SHA, or tag?"
        options:
          - Branch name
          - Commit SHA
          - Tag
        default: Branch name
      gitRef:
        description: "Input branch name, commit SHA, or tag"
        required: true
        type: string
        default: main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy-stubs-to-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
          ref: ${{ inputs.gitRef }}

      - name: Set commit SHA
        if: github.event.inputs.refType == 'Commit SHA'
        run: echo GIT_REF_SHA=${GIT_REF} >> $GITHUB_ENV
        env:
          GIT_REF: ${{ inputs.gitRef }}

      - name: Set commit SHA by branch name
        if: github.event.inputs.refType == 'Branch name'
        run: echo GIT_REF_SHA=$(git log -1 ${GIT_REF} --pretty=format:%H) >> $GITHUB_ENV
        env:
          GIT_REF: ${{ inputs.gitRef }}

      - name: Set commit SHA by tag
        if: github.event.inputs.refType == 'Tag'
        run: echo GIT_REF_SHA=$(git rev-list -n 1 ${GIT_REF}) >> $GITHUB_ENV
        env:
          GIT_REF: ${{ inputs.gitRef }}

      - name: Set tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set current datetime
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version-file: .nvmrc

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@d78e1a4a9656d3b223e59b80676a797f20093133
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          role-to-assume: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN_MOCKS }}
          aws-region: "eu-west-2"

      - name: Install dependencies
        run: npm ci

      - name: Build stubs
        run: npm run build:stubs

      - name: Deploy stubs
        uses: govuk-one-login/devplatform-upload-action@b7bc01ed6e0b61d54f42e7f3d12dd3fdbb0f172a
        with:
          artifact-bucket-name: ${{ secrets.DEV_ARTIFACT_BUCKET_NAME_MOCKS }}
          signing-profile-name: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}
          working-directory: ./solutions/stubs
          template-file: .aws-sam/build/template.yaml
